services:
  app:
    container_name: app
    image: krisaff84/lyria:latest

    env_file:
      - .env
      
    networks:
      - backend
    restart: always
    logging: 
        driver: "json-file"
        options: 
          max-size: "10m"
          max-file: "3"
    
  nginx: 
    image: nginx:alpine3.18
    container_name: nginx
    ports:
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend
    depends_on:
      - app
    restart: always
    logging: 
        driver: "json-file"
        options: 
          max-size: "10m"
          max-file: "3"

networks: 
  frontend:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/112
  backend: