services:
  app:
    container_name: app
    image: krisaff84/lyria:latest

    environment:
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - CLOUDFRONT_URL=${CLOUDFRONT_URL}
      - DEBUG=${DEBUG}
      - SONG_ORDER=${SONG_ORDER}
      - SECRET_KEY=${SECRET_KEY}
      
    networks:
      - backend
    restart: always
    logging: 
        driver: "json-file"
        options: 
          max-size: "10m"
          max-file: "3"
    
  nginx: 
    image: nginx:alpine3.18
    container_name: nginx
    ports:
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend
    depends_on:
      - app
    restart: always
    logging: 
        driver: "json-file"
        options: 
          max-size: "10m"
          max-file: "3"

networks: 
  frontend:
  backend: