name: Create Image

on:
  pull_request:
    types: [ closed ]
    paths-ignore:
      - 'README.md'
      - 'bucketActions/**'
      - 'ci_scripts/**'
      - 'terraform/**'
      - '.gitignore'
       
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  STAGING_INSTANCE_ID: 'i-0a196b4cdcbc3ed7e'

jobs:
  create_image:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install boto3
        run: pip install boto3

      - name: Create AMI from instance 
        working-directory: ./ci_scripts
        run: python create_ami.py

      - name: Stop Staging Server
        if: always()
        working-directory: ./ci_scripts
        run: python stop_staging_server.py
    
  stop_staging_server:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install boto3
        run: pip install boto3

      - name: Stop Staging Server
        working-directory: ./ci_scripts
        run: python stop_staging_server.py